### PR TITLE
Manage installation of the external project manually.

### LINKED ISSUE #2: Package doesn't build tinydir correctly in a debian context
The packaging build for this repo is failing. http://build.ros2.org/job/Cbin_uB64__tinydir_vendor__ubuntu_bionic_amd64__binary/1/

The issue is related to the build and installation of the tinydir source itself rather than the tinydir_vendor bits, which install fine if you turn off the external project.

```
13:19:31 [ 87%] Performing install step for 'tinydir-1.2.4'
13:19:31 cd /tmp/binarydeb/ros-crystal-tinydir-vendor-1.0.0/obj-x86_64-linux-gnu/tinydir-1.2.4/src/tinydir-1.2.4 && make install
13:19:31 make[5]: Entering directory '/tmp/binarydeb/ros-crystal-tinydir-vendor-1.0.0/obj-x86_64-linux-gnu/tinydir-1.2.4/src/tinydir-1.2.4'
13:19:31 Install the project...
13:19:31 -- Install configuration: ""
13:19:31 CMake Error at cmake_install.cmake:41 (file):
13:19:31   file cannot create directory: /opt/ros/crystal/include/tinydir.  Maybe need
13:19:31   administrative privileges.
```

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Connects to #2, fixes #2

This change, mostly influenced by https://github.com/ament/uncrustify_vendor/,
modifies the cmake arguments for tinydir installation to install it into
the build directory of the vendor package, then the vendor package takes
that result and installs it to the ultimate target during the vendor
package's install phase.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6056/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2545/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4994/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5921/)

**Comment by nuclearsandwich** [comment]
Building a package with this change is successful and the package appears well-formed:

```
drwxr-xr-x root/root         0 2019-01-22 14:52 ./
drwxr-xr-x root/root         0 2019-01-22 14:52 ./opt/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./opt/ros/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./opt/ros/crystal/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./opt/ros/crystal/include/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./opt/ros/crystal/include/tinydir/
-rw-r--r-- root/root     18362 2018-10-22 19:04 ./opt/ros/crystal/include/tinydir/tinydir.h
drwxr-xr-x root/root         0 2019-01-22 14:52 ./opt/ros/crystal/share/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./opt/ros/crystal/share/tinydir_vendor/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./opt/ros/crystal/share/tinydir_vendor/cmake/
-rw-r--r-- root/root       353 2019-01-22 14:52 ./opt/ros/crystal/share/tinydir_vendor/cmake/tinydir_vendorConfig-version.cmake
-rw-r--r-- root/root       342 2019-01-22 14:52 ./opt/ros/crystal/share/tinydir_vendor/cmake/tinydir_vendorConfig.cmake
drwxr-xr-x root/root         0 2019-01-22 14:52 ./usr/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./usr/share/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./usr/share/doc/
drwxr-xr-x root/root         0 2019-01-22 14:52 ./usr/share/doc/ros-crystal-tinydir-vendor/
-rw-r--r-- root/root       271 2019-01-22 14:52 ./usr/share/doc/ros-crystal-tinydir-vendor/changelog.Debian.gz
```

**Comment by AAlon** [comment]
Looks good, thanks for the fix!

**Comment by nuclearsandwich** [comment]
Closing the loop, releasing 1.0.1 allowed us to build the package and it will be released to the main ROS 2 repository in tomorrow's package sync.

**Pull request merged**
